language: node_js
node_js: node

cache:
  npm: false # avoid caching empty node_modules

before_script:
  - npx prettier --check .
  - ( cd webapp && npm ci && npx eslint --ext ts --max-warnings 0 . )
script: make
after_script:
  - set -e
  - out=`git status --porcelain`; [ -z "$out" ] || ( git diff && exit 1 )
