language: node_js
node_js: node

cache:
  npm: false # avoid caching empty node_modules

before_script: npx prettier --check .
script: true # TODO should be `make` but geco is not public
after_script: git status --porcelain
